### PR TITLE
More consistent (?) packParameter

### PR DESCRIPTION
**Pull request by brucemiller**
Several related bits
* Got rid of `STRICT_ARG`
* tried to be more consistent with where `packParameter` was called
* Added option `macrobody` option for DefParameter, which calls `packParameter` on the arg value.

Not too sure about the name `macrobody`, and maybe this carries "structured" arguments a bit too far?

But it seems to work!

### CODE REVIEW

**Comment by dginev** [comment]
Reading through the code, the new logic looks good!

I find the name `macrobody` rather confusing myself, since we're only half-emulating TeX and half-rerouting bits of logic. I would probably prefer a name closer to what the option *does* in LaTeXML-land, so that it is easy to predict when reading the definitions. And then also follow the usual option naming scheme... So maybe:

`captureArgTokens=>1`, in the spirit of `captureBody=>1` ?

**Comment by brucemiller** [comment]
Hmm, closer, but it doesn't really capture anything. Maybe go full-on literal: `pack_parameters` ?
Hmm^2, it seems we've got both CamelCase and underscore_separated options to various things.

**Comment by dginev** [comment]
Sure, `pack_parameters` or `packParameters` also sound good to me.

As to the snake_case vs camelCase, that would be a very large cosmetic refactor that will also break any external third-party bindings that do customization. The main latexml customization docs have mostly camelCase I believe, e.g. `beforeDigest`, `afterConstruct` and so on... And I'm seeing this new option switch you added somewhere in that territory.

**Comment by dginev** [comment]
Still looks great on a second read, LGTM.

**Pull request merged**
